export const SET_LOADING = "SET_LOADING";
//Order types
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

//fetch Single Order types
export const SINGLE_ORDER_FETCH_SUCCESS = "SINGLE_ORDER_FETCH_SUCCESS";
export const SINGLE_ORDER_FETCH_FAIL = "SINGLE_ORDER_FETCH_FAIL";

//Pay Order types
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

//Order List types
export const ORDER_MY_LIST_SUCCESS = "ORDER_MY_LIST_SUCCESS";
export const ORDER_MY_LIST_FAIL = "ORDER_MY_LIST_FAIL";
export const ORDER_MY_LIST_RESET = "ORDER_MY_LIST_RESET";
