//Product Types
//fetch all products action types
export const SET_LOADING = 'SET_LOADING';
export const PRODUCTS_LIST_FETCH_SUCCESS = 'PRODUCTS_LIST_FETCH_SUCCESS';
export const PRODUCTS_LIST_FETCH_FAIL = 'PRODUCTS_LIST_FETCH_FAIL';

//fetch single product action types
export const SINGLE_PRODUCT_FETCH_SUCCESS = 'SINGLE_PRODUCT_FETCH_SUCCESS';
export const SINGLE_PRODUCT_FETCH_FAIL = 'SINGLE_PRODUCT_FETCH_FAIL';
//Product delete by admin only
export const PRODUCT_CREATE_BY_ADMIN_SUCCESS = "PRODUCT_CREATE_BY_ADMIN_SUCCESS";
export const PRODUCT_CREATE_BY_ADMIN_FAIL = "PRODUCT_CREATE_BY_ADMIN_FAIL";
//Product delete by admin only
export const PRODUCT_DELETE_BY_ADMIN_SUCCESS = "PRODUCT_DELETE_BY_ADMIN_SUCCESS";
export const PRODUCT_DELETE_BY_ADMIN_FAIL = "PRODUCT_DELETE_BY_ADMIN_FAIL";
//Product Update  for admin only
export const PRODUCT_UPDATE_BY_ADMIN_SUCCESS = "PRODUCT_UPDATE_BY_ADMIN_SUCCESS";
export const PRODUCT_UPDATE_BY_ADMIN_FAIL = "PRODUCT_UPDATE_BY_ADMIN_FAIL";
export const PRODUCT_UPDATE_BY_ADMIN_RESET = "PRODUCT_UPDATE_BY_ADMIN_RESET";
//Product create Review types
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";
//Get top rated Products
export const PRODUCTS_TOP_RATED_FETCH_SUCCESS = "PRODUCTS_TOP_RATED_FETCH_SUCCESS";
export const PRODUCTS_TOP_RATED_FETCH_FAIL = "PRODUCTS_TOP_RATED_FETCH_FAIL";
